name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-debug:
    name: build (Debug)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      - name: Restore dependencies
        run: dotnet restore ./3rdEyeGitDemo.csproj
      - name: Build Debug
        run: dotnet build ./3rdEyeGitDemo.csproj --configuration Debug --no-restore -warnaserror

  build-release:
    name: build (Release)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      - name: Restore dependencies
        run: dotnet restore ./3rdEyeGitDemo.csproj
      - name: Build Release
        run: dotnet build ./3rdEyeGitDemo.csproj --configuration Release --no-restore -warnaserror
